name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        echo -e "[url \"https://github.com/\"]\n\tinsteadOf = ssh://git@github.com/" > ~/.gitconfig
        yarn install && yarn build
    - uses: actions/download-artifact@v1
      with:
        name: stremio-web
    - run: zip -r stremio-web.zip ./stremio-web
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: stremio-web.zip
        asset_name: stremio-web
        tag: ${{ github.ref }}
        overwrite: true
